# Early-Stage Diabetes Risk Prediction

## 1. Dataset Description

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/diabetes_dataset.csv")

df.head()

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1

In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 100000
Number of columns: 31

In [5]:
df.columns

Index(['age', 'gender', 'ethnicity', 'education_level', 'income_level',
       'employment_status', 'smoking_status', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day',
       'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'bmi', 'waist_to_hip_ratio', 'systolic_bp',
       'diastolic_bp', 'heart_rate', 'cholesterol_total', 'hdl_cholesterol',
       'ldl_cholesterol', 'triglycerides', 'glucose_fasting',
       'glucose_postprandial', 'insulin_level', 'hba1c', 'diabetes_risk_score',
       'diabetes_stage', 'diagnosed_diabetes'],
      dtype='str')

In [6]:
df.dtypes

age                                     int64
gender                                    str
ethnicity                                 str
education_level                           str
income_level                              str
employment_status                         str
smoking_status                            str
alcohol_consumption_per_week            int64
physical_activity_minutes_per_week      int64
diet_score                            float64
sleep_hours_per_day                   float64
screen_time_hours_per_day             float64
family_history_diabetes                 int64
hypertension_history                    int64
cardiovascular_history                  int64
bmi                                   float64
waist_to_hip_ratio                    float64
systolic_bp                             int64
diastolic_bp                            int64
heart_rate                              int64
cholesterol_total                       int64
hdl_cholesterol                         int64
ldl_cholesterol                         int64
triglycerides                           int64
glucose_fasting                         int64
glucose_postprandial                    int64
insulin_level                         float64
hba1c                                 float64
diabetes_risk_score                   float64
diabetes_stage                            str
diagnosed_diabetes                      int64
dtype: object

In [7]:
df["diagnosed_diabetes"].value_counts()

diagnosed_diabetes
1    59998
0    40002
Name: count, dtype: int64

In [8]:
target_distribution = df["diagnosed_diabetes"].value_counts(normalize=True) * 100

print(target_distribution)

diagnosed_diabetes
1    59.998
0    40.002
Name: proportion, dtype: float64

In [9]:
df.isnull().sum()

age                                   0
gender                                0
ethnicity                             0
education_level                       0
income_level                          0
employment_status                     0
smoking_status                        0
alcohol_consumption_per_week          0
physical_activity_minutes_per_week    0
diet_score                            0
sleep_hours_per_day                   0
screen_time_hours_per_day             0
family_history_diabetes               0
hypertension_history                  0
cardiovascular_history                0
bmi                                   0
waist_to_hip_ratio                    0
systolic_bp                           0
diastolic_bp                          0
heart_rate                            0
cholesterol_total                     0
hdl_cholesterol                       0
ldl_cholesterol                       0
triglycerides                         0
glucose_fasting                       0
glucose_postprandial                  0
insulin_level                         0
hba1c                                 0
diabetes_risk_score                   0
diabetes_stage                        0
diagnosed_diabetes                    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 100000 non-null  int64
 1   gender                              100000 non-null  str
 2   ethnicity                           100000 non-null  str
 3   education_level                     100000 non-null  str
 4   income_level                        100000 non-null  str
 5   employment_status                   100000 non-null  str
 6   smoking_status                      100000 non-null  str
 7   alcohol_consumption_per_week        100000 non-null  int64
 8   physical_activity_minutes_per_week  100000 non-null  int64
 9   diet_score                          100000 non-null  float64
 10  sleep_hours_per_day                 100000 non-null  float64
 11  screen_time_hours_per_day           100000 non-null  float64
 12  family_history_diabetes             100000 non-null  int64
 13  hypertension_history                100000 non-null  int64
 14  cardiovascular_history              100000 non-null  int64
 15  bmi                                 100000 non-null  float64
 16  waist_to_hip_ratio                  100000 non-null  float64
 17  systolic_bp                         100000 non-null  int64
 18  diastolic_bp                        100000 non-null  int64
 19  heart_rate                          100000 non-null  int64
 20  cholesterol_total                   100000 non-null  int64
 21  hdl_cholesterol                     100000 non-null  int64
 22  ldl_cholesterol                     100000 non-null  int64
 23  triglycerides                       100000 non-null  int64
 24  glucose_fasting                     100000 non-null  int64
 25  glucose_postprandial                100000 non-null  int64
 26  insulin_level                       100000 non-null  float64
 27  hba1c                               100000 non-null  float64
 28  diabetes_risk_score                 100000 non-null  float64
 29  diabetes_stage                      100000 non-null  str
 30  diagnosed_diabetes                  100000 non-null  int64
dtypes: float64(8), int64(16), str(7)
memory usage: 23.7 MB

In [12]:
feature_info = pd.DataFrame({
    "Feature": df.columns,
    "Data Type": df.dtypes.astype(str)
})

feature_info

,Feature,Data Type
age,age,int64
gender,gender,str
ethnicity,ethnicity,str
education_level,education_level,str
income_level,income_level,str
employment_status,employment_status,str
smoking_status,smoking_status,str
alcohol_consumption_per_week,alcohol_consumption_per_week,int64
physical_activity_minutes_per_week,physical_activity_minutes_per_week,int64
diet_score,diet_score,float64
sleep_hours_per_day,sleep_hours_per_day,float64
screen_time_hours_per_day,screen_time_hours_per_day,float64
family_history_diabetes,family_history_diabetes,int64
hypertension_history,hypertension_history,int64
cardiovascular_history,cardiovascular_history,int64
bmi,bmi,float64
waist_to_hip_ratio,waist_to_hip_ratio,float64
systolic_bp,systolic_bp,int64
diastolic_bp,diastolic_bp,int64
heart_rate,heart_rate,int64
cholesterol_total,cholesterol_total,int64
hdl_cholesterol,hdl_cholesterol,int64
ldl_cholesterol,ldl_cholesterol,int64
triglycerides,triglycerides,int64
glucose_fasting,glucose_fasting,int64
glucose_postprandial,glucose_postprandial,int64
insulin_level,insulin_level,float64
hba1c,hba1c,float64
diabetes_risk_score,diabetes_risk_score,float64
diabetes_stage,diabetes_stage,str
diagnosed_diabetes,diagnosed_diabetes,int64

In [13]:
target_column = "diagnosed_diabetes"

X = df.drop(columns=[target_column])
y = df[target_column]

print("Target variable:", target_column)
print("Number of input features:", X.shape[1])
print("Target classes:", sorted(y.unique()))

Target variable: diagnosed_diabetes
Number of input features: 30
Target classes: [np.int64(0), np.int64(1)]

## Dataset Source

**Dataset Name:** Diabetes Health Indicators Dataset

**Source:** Kaggle — Mohan Krishna Thalla

**Dataset Link:** https://www.kaggle.com/datasets/mohankrishnathalla/diabetes-health-indicators-dataset

**Dataset Type:** Synthetic patient health data

**Target Variable:** `diagnosed_diabetes`

**Target Encoding:**
- `0` → No Diabetes
- `1` → Diabetes